In [1]:
print("kartik dulariya")

kartik dulariya

In [2]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [28]:
import pandas as pd

In [3]:
x = {
    "name":[None,'ashish','mufid','gorave'],
    "marks":[92,78,None,82],
    "city":['jaipur','kota',None,'dosa']
}

In [4]:
df = pd.DataFrame(x)

In [6]:
df

     name  marks    city
0    None   92.0  jaipur
1  ashish   78.0    kota
2   mufid    NaN    None
3  gorave   82.0    dosa

In [7]:
df['marks']

0    92.0
1    78.0
2     NaN
3    82.0
Name: marks, dtype: float64

In [8]:
df['name'][1:3]

1    ashish
2     mufid
Name: name, dtype: object

In [12]:
y = pd.read_csv("C:\\Users\\de\\Downloads\\abc.csv")

In [13]:
y

  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23

In [14]:
y.columns

Index(['student', 'language', 'science', 'maths', 'history'], dtype='object')

# df.loc

In [9]:
#df.loc[row_range'column_name]

In [9]:
x

{'name': [None, 'ashish', 'mufid', 'gorave'],
 'marks': [92, 78, None, 82],
 'city': ['jaipur', 'kota', None, 'dosa']}

In [16]:
df = pd.DataFrame(x)

In [17]:
df.loc[2:4,['name','marks']]

     name  marks
2   mufid    NaN
3  gorave   82.0

In [20]:
df.loc[2:3,: ]

     name  marks  city
2   mufid    NaN  None
3  gorave   82.0  dosa

# df.iloc

In [11]:
#df.iloc[row_range,coulmn_range]

In [18]:
x

{'name': [None, 'ashish', 'mufid', 'gorave'],
 'marks': [92, 78, None, 82],
 'city': ['jaipur', 'kota', None, 'dosa']}

In [19]:
df.iloc[2:4,[1,2]]

   marks  city
2    NaN  None
3   82.0  dosa

# df.head

In [20]:
df.head(3)

  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32

# df.tail

In [18]:
df.tail(2)

  student  language  science  maths  history
5    prem        90       45     45       34
6  carrol        50       90     45       23

In [19]:
df.tail(3)

  student  language  science  maths  history
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23

# update in information

In [21]:
df

     name  marks    city
0    None   92.0  jaipur
1  ashish   78.0    kota
2   mufid    NaN    None
3  gorave   82.0    dosa

In [25]:
df["name"][2]="ram"

C:\Users\de\AppData\Local\Temp\ipykernel_5428\2148252747.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["name"][2]="ram"
C:\Users\de\AppData\Local\Temp\ipykernel_5428\2148252747.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["name"][2]="ram"

In [26]:
df

     name  marks    city
0    None   92.0  jaipur
1  ashish   78.0    kota
2     ram    NaN    None
3     ram   82.0    dosa

# df.describe

In [34]:
data = pd.read_csv("C:\\Users\\de\\Downloads\\data.csv")

description = data.describe()
print(description)

                 id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000

       smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
count       569.000000        569.000000      569.000000           569.000000
mean          0.096360          0.104341        0.088799             0.048919
std           0.014064          0.052813        0.079720             0.038803
min           0.052630          0.019380        0.000000             0.000000
25%           0.086370          0.064920        0.029560             0.020310
50%           0.095870          0.092630        0.061540             0.033500
75%           0.105300          0.130400        0.130700             0.074000
max           0.163400          0.345400        0.426800             0.201200

       symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
count     569.000000  ...    569.000000     569.000000       569.000000
mean        0.181162  ...     16.269190      25.677223       107.261213
std         0.027414  ...      4.833242       6.146258        33.602542
min         0.106000  ...      7.930000      12.020000        50.410000
25%         0.161900  ...     13.010000      21.080000        84.110000
50%         0.179200  ...     14.970000      25.410000        97.660000
75%         0.195700  ...     18.790000      29.720000       125.400000
max         0.304000  ...     36.040000      49.540000       251.200000

        area_worst  smoothness_worst  compactness_worst  concavity_worst  \
count   569.000000        569.000000         569.000000       569.000000
mean    880.583128          0.132369           0.254265         0.272188
std     569.356993          0.022832           0.157336         0.208624
min     185.200000          0.071170           0.027290         0.000000
25%     515.300000          0.116600           0.147200         0.114500
50%     686.500000          0.131300           0.211900         0.226700
75%    1084.000000          0.146000           0.339100         0.382900
max    4254.000000          0.222600           1.058000         1.252000

       concave points_worst  symmetry_worst  fractal_dimension_worst
count            569.000000      569.000000               569.000000
mean               0.114606        0.290076                 0.083946
std                0.065732        0.061867                 0.018061
min                0.000000        0.156500                 0.055040
25%                0.064930        0.250400                 0.071460
50%                0.099930        0.282200                 0.080040
75%                0.161400        0.317900                 0.092080
max                0.291000        0.663800                 0.207500

[8 rows x 31 columns]

In [37]:
data = pd.read_csv("C:\\Users\\de\\Downloads\\abc.csv")

description = data.describe()
print(description)

        language    science      maths    history
count   7.000000   7.000000   7.000000   7.000000
mean   54.285714  53.000000  43.285714  42.857143
std    35.523299  22.015146  23.746679  17.062909
min    10.000000  23.000000  12.000000  23.000000
25%    25.000000  39.500000  33.000000  33.000000
50%    50.000000  56.000000  45.000000  34.000000
75%    90.000000  61.500000  45.000000  55.000000
max    90.000000  90.000000  90.000000  67.000000

# convert file into csv or excel

In [46]:
df = pd.read_csv("C:\\Users\\de\\Downloads\\abc.csv")

In [47]:
df.to_csv("abc.csv",index= False)

# Data Cleaning

# df.columns

In [52]:
df.columns = ('student','science','maths','language','history')
df

  student  science  maths  language  history
0   kumar       90     56        34       34
1   kevin       10     34        32       67
2   sammy       90     23        12       32
3  janice       20     67        90       45
4   peter       30     56        45       65
5    prem       90     45        45       34
6  carrol       50     90        45       23

# pd.isnull

In [54]:
data = {'a': [1,3,5,None],
        'b': [7,9,None,11],
        'c': [13,None,15,17]}

df=pd.DataFrame(data)

null_values = pd.isnull(df)

print(null_values)

       a      b      c
0  False  False  False
1  False  False   True
2  False   True  False
3   True  False  False

In [61]:
a =pd.isnull(df)
print(a)
df.isnull().sum()

       A      B      C
0  False  False  False
1  False  False  False
2  False   True  False
3   True  False  False

A    1
B    1
C    0
dtype: int64

In [62]:
df.isnull().sum()

A    1
B    1
C    0
dtype: int64

# `pd.notnull

In [55]:
data = {'A': [1,3,5,None],
        'B': [7,9,None,11],
        'C': [13,None,15,17]}

df = pd.DataFrame(data)

not_null_values = pd.notnull(df)

print(not_null_values)

       A      B      C
0   True   True   True
1   True   True  False
2   True  False   True
3  False   True   True

# df.dropna()

In [56]:
data = {'A': [1,3,5,None],
        'B': [7,9,None,11],
        'C': [13,None,15,17]}

df = pd.DataFrame(data)

clean_df = df.dropna()

print(clean_df)

     A    B     C
0  1.0  7.0  13.0

# df.dropna(axis=1)

In [59]:
data = {'A': [1,3,5,None],
        'B': [7,9,None,11],
        'C': [13,6,15,17]}

df = pd.DataFrame(data)

clean_df = df.dropna(axis=1)

print(clean_df)

    C
0  13
1   6
2  15
3  17

# df.dropna(axis=1, thresh=n)

In [74]:
data = {'A': [1,3,5,None],
        'B': [None,9,None,11],
        'C': [13,6,15,17]}

df = pd.DataFrame(data)

clean_df = df.dropna(axis=1,thresh=3)

print(clean_df)

     A   C
0  1.0  13
1  3.0   6
2  5.0  15
3  NaN  17

In [70]:
data = {'A': [3,5,None,None],
        'B': [9,None,11,12],
        'C': [None,15,17,None]}

df = pd.DataFrame(data)

clean_df = df.dropna(axis=1,thresh=3)

print(clean_df)

      B
0   9.0
1   NaN
2  11.0
3  12.0

In [75]:
data = {'A': [3,5,None,None],
        'B': [9,None,11,12],
        'C': [None,15,17,None]}

df = pd.DataFrame(data)

clean_df = df.dropna(axis=1,thresh=2)

print(clean_df)

     A     B     C
0  3.0   9.0   NaN
1  5.0   NaN  15.0
2  NaN  11.0  17.0
3  NaN  12.0   NaN

# df.fillna(x)

In [71]:
data = {'A': [1,3,5,None],
        'B': [None,9,None,11],
        'C': [13,6,15,17]}

df = pd.DataFrame(data)

clean_df = df.fillna(0)

print(clean_df)

     A     B   C
0  1.0   0.0  13
1  3.0   9.0   6
2  5.0   0.0  15
3  0.0  11.0  17

In [72]:
data = {'A': [None,3,5,None],
        'B': [None,9,None,11],
        'C': [13,None,None,17]}

df = pd.DataFrame(data)

clean_df = df.fillna(0)

print(clean_df)

     A     B     C
0  0.0   0.0  13.0
1  3.0   9.0   0.0
2  5.0   0.0   0.0
3  0.0  11.0  17.0

# x.replace

In [78]:
x = pd.Series([0,2,4,6,8])

new_x = x.replace([0,4], ['one','three'])

print(new_x)

0      one
1        2
2    three
3        6
4        8
dtype: object

In [79]:
x = pd.Series([0,2,4,6,8])

new_x = x.replace([0,4,6,8], [1,3,4,5])

print(new_x)

0    1
1    2
2    3
3    4
4    5
dtype: int64

# new dada concat in csv file

In [29]:
new = {
    'student' :["kartik"],
    'language' :[80], 
    'science' :[70], 
    'maths' :[44], 
    'history' :[78]
}

In [30]:
import pandas as pd

# Your existing DataFrame (df)
# Your new dictionary
new = {
    'student' :["kartik"],
    'language' :[80], 
    'science' :[70], 
    'maths' :[44], 
    'history' :[78]
}

# 1. Convert dictionary to a temporary DataFrame
new_df = pd.DataFrame(new)

# 2. Concatenate them together
df = pd.concat([df, new_df], ignore_index=True)

print(df.tail())

  student  language  science  maths  history
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23
7  kartik        80       70     44       78

In [31]:
df

  student  language  science  maths  history
0   kumar        90       56     34       34
1   kevin        10       34     32       67
2   sammy        90       23     12       32
3  janice        20       67     90       45
4   peter        30       56     45       65
5    prem        90       45     45       34
6  carrol        50       90     45       23
7  kartik        80       70     44       78

In [ ]:
data = pd.DataFrame({
    'name': ['kartik','gourav','ashish','mufid'],
    'maths':['70','76','75','77'],
    'english':['80','82','83','85'],
    'hindi':['90','92','91','89'],
    'science':['65','67','66','69']
})